"""
Generate zcash.conf files for each build phase.

Each phase of the regtest chain build uses a different zcashd version.
Each version requires a zcash.conf that:
  1. Enables regtest mode
  2. Sets RPC credentials
  3. Lists -nuparams for ALL network upgrades the version knows about
  4. Adds any version-specific flags (e.g., -allowdeprecated for v5+)

CRITICAL: Each zcashd version must only receive nuparams for the NUs it
recognizes. Passing an unknown branch ID will cause zcashd to error.
For example, v1.0.x doesn't know about Overwinter at all, and v2.0.x
doesn't know about Blossom. The `known_nus` field in each NetworkUpgrade
definition (constants.py) controls which nuparams are included.

The nuparams are cumulative: each phase includes all prior NUs' activation
heights plus its own. This tells zcashd where each upgrade boundary falls
in the regtest chain.
"""

import logging
import os

from lib.constants import (
    NETWORK_UPGRADES,
    RPC_USER,
    RPC_PASSWORD,
    RPC_PORT_PRIMARY,
    RPC_PORT_EXTERNAL,
    EXPORTS_DIR,
    get_nu_by_id,
)

logger = logging.getLogger(__name__)


def generate_conf(phase_index: int, datadir: str, rpcport: int = RPC_PORT_PRIMARY,
                  miner_address: str | None = None) -> str:
    """
    Generate the contents of zcash.conf for a given build phase.

    Args:
        phase_index:    Index into NETWORK_UPGRADES (0 = Sprout, 1 = Overwinter, ...)
        datadir:        Data directory path (for the exportdir setting)
        rpcport:        RPC port (18443 for primary wallet, 18444 for external)
        miner_address:  If set, mine coinbase directly to this shielded address.
                        Only supported from Heartwood (phase 4) onwards (ZIP 213).

    Returns:
        The complete zcash.conf content as a string.
    """
    current_nu = NETWORK_UPGRADES[phase_index]
    lines = []

    # Header comment
    lines.append(f"# zcash.conf for phase {phase_index}: {current_nu.name}")
    lines.append(f"# zcashd version: {current_nu.zcashd_version}")
    lines.append("# Generated by zcash-regtest-wallet-builder/lib/conf_generator.py")
    lines.append("")

    # Core settings
    lines.append("# === Core Settings ===")
    lines.append("regtest=1")
    lines.append("server=1")
    lines.append(f"rpcuser={RPC_USER}")
    lines.append(f"rpcpassword={RPC_PASSWORD}")
    lines.append(f"rpcport={rpcport}")
    lines.append("")

    # Network settings: disable all external connectivity.
    # In regtest mode we're mining locally; no peers needed.
    lines.append("# === Network ===")
    lines.append("listen=0")
    lines.append("listenonion=0")
    lines.append("")

    # Indexing: enable txindex so z_viewtransaction can look up any tx.
    lines.append("# === Indexing ===")
    lines.append("txindex=1")
    lines.append("")

    # Export directory for z_exportwallet
    lines.append("# === Export ===")
    lines.append(f"exportdir={EXPORTS_DIR}")
    lines.append("")

    # Network upgrade activation heights.
    # Only include NUs that this version's codebase recognizes.
    nuparams_lines = _build_nuparams(phase_index)
    if nuparams_lines:
        lines.append("# === Network Upgrade Activation Heights ===")
        lines.append("# Each nuparams line tells zcashd at which regtest block height")
        lines.append("# to activate a network upgrade. Heights are cumulative across")
        lines.append("# all prior phases.")
        for line in nuparams_lines:
            lines.append(line)
        lines.append("")

    # Version-specific deprecated-feature flags
    if current_nu.extra_conf:
        lines.append("# === Deprecated Feature Flags ===")
        lines.append("# zcashd v5.0+ deprecated many RPC methods. We re-enable")
        lines.append("# them because our build scripts use both legacy and modern APIs.")
        for opt in current_nu.extra_conf:
            lines.append(opt)
        lines.append("")

    # Miner address (Heartwood+ only)
    if miner_address and phase_index >= 4:
        lines.append("# === Shielded Mining (Heartwood+, ZIP 213) ===")
        lines.append("# Mine coinbase directly to a shielded address.")
        lines.append(f"mineraddress={miner_address}")
        lines.append("")

    return "\n".join(lines) + "\n"


def _build_nuparams(phase_index: int) -> list[str]:
    """
    Build the list of nuparams lines for a given phase.

    The current phase's zcashd version only knows about certain NUs (listed
    in its `known_nus` field). For each known NU, we look up its activation
    height and emit a nuparams line.

    Returns a list of config lines like:
        nuparams=5ba81b19:200
        nuparams=76b809bb:350
    """
    current_nu = NETWORK_UPGRADES[phase_index]
    result = []

    for nu_id in current_nu.known_nus:
        nu = get_nu_by_id(nu_id)
        if nu.branch_id is None:
            continue  # Sprout has no branch ID
        # Add a comment explaining which NU this is
        result.append(f"# {nu.name} (phase {nu.phase})")
        result.append(f"nuparams={nu.branch_id}:{nu.activation_height}")

    return result


def write_conf(phase_index: int, datadir: str, rpcport: int = RPC_PORT_PRIMARY,
               miner_address: str | None = None) -> str:
    """
    Write zcash.conf to the specified data directory.

    Args:
        phase_index:    Phase number (0-8)
        datadir:        zcashd data directory (e.g., /data/primary)
        rpcport:        RPC port
        miner_address:  Optional shielded mining address (Heartwood+)

    Returns:
        Path to the written zcash.conf file.
    """
    conf_content = generate_conf(phase_index, datadir, rpcport, miner_address)
    conf_path = os.path.join(datadir, "zcash.conf")

    os.makedirs(datadir, exist_ok=True)
    with open(conf_path, "w", encoding="utf8") as f:
        f.write(conf_content)

    logger.info("Wrote zcash.conf for phase %d (%s) to %s",
                phase_index, NETWORK_UPGRADES[phase_index].name, conf_path)
    return conf_path


def write_external_conf(phase_index: int) -> str:
    """
    Write zcash.conf for the external (throwaway) wallet.

    The external wallet is used solely for generating addresses that the
    primary wallet doesn't control. It uses a separate data directory and
    RPC port.

    Args:
        phase_index: Phase number (determines which NUs to activate)

    Returns:
        Path to the written zcash.conf file.
    """
    return write_conf(
        phase_index=phase_index,
        datadir=os.path.join(
            "/data/external",
            f"phase_{phase_index:02d}",
        ),
        rpcport=RPC_PORT_EXTERNAL,
    )
