"""
Import foreign keys into the primary wallet.

This module generates keys that are NOT derived from the primary wallet's
HD seed and imports them, exercising every import code path in zcashd:

  TRANSPARENT (random keys, no zcashd needed to generate):
    1. importprivkey     -- random WIF private key (spendable)
    2. importaddress     -- random address string (watch-only)
    3. importaddress+p2sh -- 1-of-1 multisig redeemScript (watch-only P2SH)
    4. importpubkey      -- random compressed pubkey (watch-only)

  SHIELDED (generated by the external zcashd, then exported+imported):
    5. z_importkey (Sprout)          -- spending key (phases 0-4)
    6. z_importkey (Sapling)         -- spending key (phases 2+)
    7. z_importviewingkey (Sprout)   -- viewing key (phases 0-4)
    8. z_importviewingkey (Sapling)  -- viewing key (phases 2+)

  NOT POSSIBLE:
    - Orchard/Unified key import (not implemented in zcashd, issue #5687)

All imports use rescan=false/"no" since we're building the chain live.
"""

import hashlib
import logging
import os
from dataclasses import dataclass

from lib.constants import (
    Pool,
    PoolPermission,
    NETWORK_UPGRADES,
)
from lib.rpc_client import ZcashRPC

logger = logging.getLogger(__name__)

# Regtest transparent address version bytes
# See https://en.bitcoin.it/wiki/List_of_address_prefixes
# Zcash regtest uses the same prefixes as testnet.
REGTEST_PRIVKEY_PREFIX = b'\xef'      # WIF prefix for regtest/testnet
REGTEST_PUBKEY_PREFIX = b'\x1d\x25'   # t-addr prefix "tm" for regtest


@dataclass
class ImportedKeys:
    """Record of all keys imported during a phase."""
    transparent_privkey: dict | None = None   # {address, wif, label}
    transparent_watchonly: dict | None = None  # {address, label}
    transparent_p2sh: dict | None = None      # {address, redeem_script, label}
    transparent_pubkey: dict | None = None     # {address, pubkey_hex, label}
    sprout_spending: dict | None = None        # {address, key, label}
    sprout_viewing: dict | None = None         # {address, key, label}
    sapling_spending: dict | None = None       # {address, key, label}
    sapling_viewing: dict | None = None        # {address, key, label}

    def to_dict(self) -> dict:
        return {k: v for k, v in {
            "transparent_privkey": self.transparent_privkey,
            "transparent_watchonly": self.transparent_watchonly,
            "transparent_p2sh": self.transparent_p2sh,
            "transparent_pubkey": self.transparent_pubkey,
            "sprout_spending": self.sprout_spending,
            "sprout_viewing": self.sprout_viewing,
            "sapling_spending": self.sapling_spending,
            "sapling_viewing": self.sapling_viewing,
        }.items() if v is not None}


def _base58check_encode(payload: bytes) -> str:
    """Base58Check encode (used for WIF keys and addresses)."""
    alphabet = b'123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz'
    checksum = hashlib.sha256(hashlib.sha256(payload).digest()).digest()[:4]
    data = payload + checksum
    # Convert to base58
    n = int.from_bytes(data, 'big')
    result = b''
    while n > 0:
        n, r = divmod(n, 58)
        result = bytes([alphabet[r]]) + result
    # Preserve leading zero bytes
    for byte in data:
        if byte == 0:
            result = bytes([alphabet[0]]) + result
        else:
            break
    return result.decode('ascii')


def _generate_random_keypair() -> tuple[bytes, bytes]:
    """Generate a random secp256k1 keypair (private key + compressed pubkey).

    Uses a simplified approach: generate a random 32-byte private key and
    derive the compressed public key. We use hashlib to avoid needing
    external crypto libraries -- this produces a valid-looking key for
    import purposes even though the pubkey derivation is simplified.

    For real secp256k1 derivation we'd need the ecdsa library, but for
    import testing we just need structurally valid keys that zcashd accepts.
    """
    # Generate random 32-byte private key
    privkey = os.urandom(32)
    # For a proper compressed pubkey we'd need secp256k1 multiplication.
    # Instead, use zcashd's validateaddress after import to verify.
    # We'll generate the privkey as WIF and let importprivkey derive the address.
    return privkey, None  # pubkey derived by zcashd on import


def _privkey_to_wif(privkey_bytes: bytes, compressed: bool = True) -> str:
    """Encode a raw private key as WIF for regtest."""
    payload = REGTEST_PRIVKEY_PREFIX + privkey_bytes
    if compressed:
        payload += b'\x01'
    return _base58check_encode(payload)


def import_keys_for_phase(primary_rpc: ZcashRPC,
                          external_rpc: ZcashRPC | None,
                          phase_index: int) -> ImportedKeys:
    """
    Import foreign keys into the primary wallet for the current phase.

    Args:
        primary_rpc:   RPC client for the primary wallet (import target)
        external_rpc:  RPC client for the external wallet (shielded key source).
                       May be None if external wallet isn't running.
        phase_index:   Current build phase

    Returns:
        ImportedKeys record of everything imported.
    """
    nu = NETWORK_UPGRADES[phase_index]
    imported = ImportedKeys()

    logger.info("Importing foreign keys for phase %d (%s)...", phase_index, nu.name)

    # ------------------------------------------------------------------
    # 1. importprivkey -- random transparent private key (spendable)
    # ------------------------------------------------------------------
    try:
        privkey_bytes, _ = _generate_random_keypair()
        wif = _privkey_to_wif(privkey_bytes)
        label = f"imported_privkey_phase{phase_index}"
        result = primary_rpc.importprivkey(wif, label, rescan=False)
        # importprivkey returns the address in v1.0.12+
        address = result if isinstance(result, str) else "unknown"
        imported.transparent_privkey = {
            "address": address, "wif": wif, "label": label,
        }
        logger.info("  importprivkey: %s", address)
    except Exception as e:
        logger.error("  importprivkey failed: %s", e)

    # ------------------------------------------------------------------
    # 2. importaddress -- random address (watch-only)
    # ------------------------------------------------------------------
    try:
        if external_rpc is not None:
            privkey2, _ = _generate_random_keypair()
            wif2 = _privkey_to_wif(privkey2)
            ext_addr = external_rpc.importprivkey(wif2, "", rescan=False)
            if isinstance(ext_addr, str) and ext_addr:
                label = f"imported_watchonly_phase{phase_index}"
                primary_rpc.importaddress(ext_addr, label, rescan=False)
                imported.transparent_watchonly = {
                    "address": ext_addr, "label": label,
                }
                logger.info("  importaddress (watch-only): %s", ext_addr)
    except Exception as e:
        logger.error("  importaddress (watch-only) failed: %s", e)

    # ------------------------------------------------------------------
    # 3. importaddress + p2sh -- 1-of-1 multisig redeemScript (watch-only)
    # The p2sh (4th) parameter was added around v2.1.0. Skip on v1.x/v2.0.x.
    # ------------------------------------------------------------------
    major = int(nu.zcashd_version.split(".")[0])
    if major >= 3 or (major == 2 and not nu.zcashd_version.startswith("2.0")):
        try:
            if external_rpc is not None:
                privkey3, _ = _generate_random_keypair()
                wif3 = _privkey_to_wif(privkey3)
                ext_addr3 = external_rpc.importprivkey(wif3, "", rescan=False)
                if isinstance(ext_addr3, str) and ext_addr3:
                    info = external_rpc.call("validateaddress", ext_addr3)
                    pubkey_hex = info.get("pubkey", "")
                    if pubkey_hex:
                        multisig = external_rpc.call(
                            "createmultisig", 1, [pubkey_hex]
                        )
                        redeem_script = multisig.get("redeemScript", "")
                        p2sh_address = multisig.get("address", "")
                        if redeem_script:
                            label = f"imported_p2sh_phase{phase_index}"
                            primary_rpc.importaddress(
                                redeem_script, label, False, True
                            )
                            imported.transparent_p2sh = {
                                "address": p2sh_address,
                                "redeem_script": redeem_script,
                                "label": label,
                            }
                            logger.info("  importaddress (p2sh): %s", p2sh_address)
        except Exception as e:
            logger.error("  importaddress (p2sh) failed: %s", e)

    # ------------------------------------------------------------------
    # 4. importpubkey -- random pubkey (watch-only)
    # Not available in v1.0.x (returns 404). Available from v1.1.x+.
    # ------------------------------------------------------------------
    # importpubkey available from ~v2.1.0+. Earlier versions return 404.
    if major >= 3 or (major == 2 and not nu.zcashd_version.startswith("2.0")):
        try:
            if external_rpc is not None:
                privkey4, _ = _generate_random_keypair()
                wif4 = _privkey_to_wif(privkey4)
                ext_addr4 = external_rpc.importprivkey(wif4, "", rescan=False)
                if isinstance(ext_addr4, str) and ext_addr4:
                    info = external_rpc.call("validateaddress", ext_addr4)
                    pubkey_hex = info.get("pubkey", "")
                    if pubkey_hex:
                        label = f"imported_pubkey_phase{phase_index}"
                        primary_rpc.importpubkey(pubkey_hex, label, rescan=False)
                        imported.transparent_pubkey = {
                            "address": ext_addr4,
                            "pubkey_hex": pubkey_hex,
                            "label": label,
                        }
                        logger.info("  importpubkey: %s", ext_addr4)
        except Exception as e:
            logger.error("  importpubkey failed: %s", e)

    # ------------------------------------------------------------------
    # 5. z_importkey (Sprout spending key)
    # Only works when external wallet can generate Sprout addresses.
    # v4.1.1+ blocks Sprout address generation during IBD, and the
    # external wallet is always in IBD (no chain data).
    # ------------------------------------------------------------------
    sprout_available = nu.pools.get(Pool.SPROUT) not in (None, PoolPermission.UNAVAILABLE)
    can_gen_sprout = sprout_available and major <= 3  # v1.x-v3.x
    if can_gen_sprout:
        try:
            if external_rpc is not None:
                has_sapling = nu.pools.get(Pool.SAPLING) != PoolPermission.UNAVAILABLE
                ext_sprout = (external_rpc.z_getnewaddress("sprout")
                              if has_sapling
                              else external_rpc.z_getnewaddress())
                sprout_sk = external_rpc.z_exportkey(ext_sprout)
                result = primary_rpc.z_importkey(sprout_sk, rescan="no")
                addr = result.get("address", ext_sprout) if isinstance(result, dict) else ext_sprout
                imported.sprout_spending = {
                    "address": addr, "key": sprout_sk,
                    "label": f"imported_sprout_sk_phase{phase_index}",
                }
                logger.info("  z_importkey (Sprout): %s", addr[:32] + "...")
        except Exception as e:
            logger.error("  z_importkey (Sprout) failed: %s", e)

    # ------------------------------------------------------------------
    # 6. z_importkey (Sapling spending key)
    # ------------------------------------------------------------------
    if nu.pools.get(Pool.SAPLING) == PoolPermission.FULL:
        try:
            if external_rpc is not None:
                ext_sapling = external_rpc.z_getnewaddress("sapling")
                sapling_sk = external_rpc.z_exportkey(ext_sapling)
                result = primary_rpc.z_importkey(sapling_sk, rescan="no")
                addr = result.get("address", ext_sapling) if isinstance(result, dict) else ext_sapling
                imported.sapling_spending = {
                    "address": addr, "key": sapling_sk,
                    "label": f"imported_sapling_sk_phase{phase_index}",
                }
                logger.info("  z_importkey (Sapling): %s", addr[:32] + "...")
        except Exception as e:
            logger.error("  z_importkey (Sapling) failed: %s", e)

    # ------------------------------------------------------------------
    # 7. z_importviewingkey (Sprout)
    # Same IBD constraint as z_importkey for Sprout (v4+ blocks it).
    # z_importviewingkey with rescan/startHeight params: v1.1.0+.
    # v1.0.x only accepts the key argument (no rescan/startHeight).
    # ------------------------------------------------------------------
    if can_gen_sprout:
        try:
            if external_rpc is not None:
                has_sapling = nu.pools.get(Pool.SAPLING) != PoolPermission.UNAVAILABLE
                ext_sprout2 = (external_rpc.z_getnewaddress("sprout")
                               if has_sapling
                               else external_rpc.z_getnewaddress())
                sprout_vk = external_rpc.z_exportviewingkey(ext_sprout2)
                result = primary_rpc.z_importviewingkey(sprout_vk, rescan="no")
                addr = result.get("address", ext_sprout2) if isinstance(result, dict) else ext_sprout2
                imported.sprout_viewing = {
                    "address": addr, "key": sprout_vk,
                    "label": f"imported_sprout_vk_phase{phase_index}",
                }
                logger.info("  z_importviewingkey (Sprout): %s", addr[:32] + "...")
        except Exception as e:
            logger.error("  z_importviewingkey (Sprout) failed: %s", e)

    # ------------------------------------------------------------------
    # 8. z_importviewingkey (Sapling)
    # Sapling viewing key import supported from v2.1.0+ (not v2.0.1).
    # The error "Currently, only Sprout zaddrs are supported" means
    # this version's z_importviewingkey doesn't handle Sapling yet.
    # ------------------------------------------------------------------
    sapling_vk_supported = (nu.pools.get(Pool.SAPLING) == PoolPermission.FULL
                            and (major >= 3 or (major == 2
                                 and not nu.zcashd_version.startswith("2.0"))))
    if sapling_vk_supported:
        try:
            if external_rpc is not None:
                ext_sapling2 = external_rpc.z_getnewaddress("sapling")
                sapling_vk = external_rpc.z_exportviewingkey(ext_sapling2)
                result = primary_rpc.z_importviewingkey(sapling_vk, rescan="no")
                addr = result.get("address", ext_sapling2) if isinstance(result, dict) else ext_sapling2
                imported.sapling_viewing = {
                    "address": addr, "key": sapling_vk,
                    "label": f"imported_sapling_vk_phase{phase_index}",
                }
                logger.info("  z_importviewingkey (Sapling): %s", addr[:32] + "...")
        except Exception as e:
            logger.error("  z_importviewingkey (Sapling) failed: %s", e)

    count = sum(1 for v in imported.to_dict().values() if v is not None)
    logger.info("Imported %d foreign keys for phase %d", count, phase_index)
    return imported
