{
 "title": "Zcash rust metrics Copy",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Verified Block Height",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "zcash_chain_verified_block_height"
    }
   ]
  },
  { "title": "Net Out", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Net OUT Messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "rate(zcash_net_out_messages[1m])",
     "legendFormat": "{{command}}"
    }
   ]
  },
  {
   "title": "Net OUT Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "rate(zcash_net_out_bytes[1m])", "legendFormat": "{{command}}" }
   ]
  },
  {
   "title": "Net Out Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 15, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(zcash_net_out_bytes_total[1m])"
    }
   ]
  },
  { "title": "Net In", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Net In Messages",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "rate(zcash_net_in_messages[1m])",
     "legendFormat": "{{command}}"
    }
   ]
  },
  {
   "title": "Net In Bytes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "rate(zcash_net_in_bytes[1m])", "legendFormat": "{{command}}" }
   ]
  },
  {
   "title": "Net In Total",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 15, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(zcash_net_in_bytes_total[1m])"
    }
   ]
  }
 ]
}