{
 "title": "Zcash rust metrics Copy",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Zcash Version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "zcashd_build_info{}" }
   ]
  },
  {
   "title": "Notes Created",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 3, "y": 0 },
   "targets": [
    { "expr": "zcash_pool_notes_created{}", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Value Pools",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 11, "y": 0 },
   "targets": [
    { "expr": "zcash_pool_value_zatoshis{}", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Value Pools",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 4, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "zcash_pool_value_zatoshis{}", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Verified Block Height",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "zcash_chain_verified_block_height"
    }
   ]
  },
  {
   "title": "Verified Block Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "zcash_chain_verified_block_total{}"
    }
   ]
  },
  { "title": "Net Out", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Net OUT Messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "rate(zcash_net_out_messages[1m])",
     "legendFormat": "{{command}}"
    }
   ]
  },
  {
   "title": "Net OUT Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "rate(zcash_net_out_bytes[1m])", "legendFormat": "{{command}}" }
   ]
  },
  {
   "title": "Net Out Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 15, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(zcash_net_out_bytes_total[1m])"
    }
   ]
  },
  { "title": "Net In", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Net In Messages",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "rate(zcash_net_in_messages[1m])",
     "legendFormat": "{{command}}"
    }
   ]
  },
  {
   "title": "Net In Bytes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 8, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "rate(zcash_net_in_bytes[1m])", "legendFormat": "{{command}}" }
   ]
  },
  {
   "title": "Net In Total",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 15, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(zcash_net_in_bytes_total[1m])"
    }
   ]
  }
 ]
}