{
 "title": "Zcash Basic Node Copy Copy",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Panel Title", "type": "timeseries", "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 } },
  {
   "title": "ZCASH VERSION",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "zcashd_build_version_info" }
   ]
  },
  {
   "title": "WALLET VERSION",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "zcashd_wallet_version_info{}" }
   ]
  },
  {
   "title": "PROTOCOL VERSION",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "zcashd_protocol_version_info{}" }
   ]
  },
  {
   "title": "Current Block Height",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "zcash_blocks{}" }
   ]
  },
  {
   "title": "Verification Progress",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "zcash_verification_progress{}" }
   ]
  },
  {
   "title": "Network",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "zcash_network_type{}" }
   ]
  },
  {
   "title": "Blocks Until EOS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "zcash_deprecation{} - zcash_blocks{}"
    }
   ]
  },
  {
   "title": "Peer Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "-zcash_total_bytes_sent" },
    { "expr": "zcash_total_bytes_recv" }
   ]
  },
  {
   "title": "Memory Info",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    { "expr": "zcash_mem_total" },
    { "expr": "zcash_mem_used{}" },
    { "expr": "zcash_mem_free" },
    { "expr": "zcash_mem_chunks_used" },
    { "expr": "zcash_mem_chunks_free" }
   ]
  },
  {
   "title": "Row title",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Pool Balances",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "zcash_transparent_pool_balance{}"
    },
    { "expr": "zcash_sprout_pool_balance{}" },
    { "expr": "zcash_sapling_pool_balance{}" }
   ]
  },
  {
   "title": "Estimated Height",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 9, "y": 36 },
   "targets": [
    { "expr": "zcash_estimated_height{}" }
   ]
  },
  {
   "title": "Zcash debug.log",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "{compose_service=\"zcashd\",container_name=\"ecc_zcashd_exporter_zcashd_1\"}"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "Size of Mempool",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "targets": [
    { "expr": "zcash_pooledtx{}" }
   ]
  },
  {
   "title": "Block Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "zcash_current_block_size{}" }
   ]
  },
  {
   "title": "Block Confirmations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "zcash_current_block_confirmations{}"
    }
   ]
  },
  {
   "title": "Chain on Disk",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "zcash_chain_size_on_disk" }
   ]
  }
 ]
}