cc_library(
    name = "consensus",
    visibility = ["//visibility:public"],
    hdrs = ["consensus.h"],
)

cc_library(
    name = "params",
    visibility = ["//visibility:public"],
    hdrs = ["params.h"],
    deps = [
        "//src:uint256",
    ],
)

cc_library(
    name = "validation",
    visibility = ["//visibility:public"],
    hdrs = ["validation.h"],
)
