cc_library(
    name = "secure",
    visibility = ["//visibility:public"],
    hdrs = ["secure.h"],
    deps = [
        "//src/support:pagelocker",
    ],
)

cc_library(
    name = "zeroafterfree",
    visibility = ["//visibility:public"],
    hdrs = ["zeroafterfree.h"],
    deps = [
        "//src/support:cleanse",
    ],
)
