.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. komodo_qt test_komodo_qt
clean: FORCE
	$(MAKE) -C .. komodo_qt_clean test_komodo_qt_clean
check: FORCE
	$(MAKE) -C .. test_komodo_qt_check
komodo-qt komodo-qt.exe: FORCE
	 $(MAKE) -C .. komodo_qt
