#!/usr/bin/env python3
# Copyright (c) 2026 The Zcash developers
# Distributed under the MIT software license, see the accompanying
# file COPYING or https://www.opensource.org/licenses/mit-license.php .

#
# Verify that the chain supply checkpoint correctly bootstraps
# nChainTotalSupply and nChainTransparentValue on a node with
# legacy block index data (lacking nChainSupplyDelta).
#
# The test uses the persistent `sprout` regtest cache (generated by
# a zcashd version older than TRANSPARENT_VALUE_VERSION) with the
# `-regtestchainsupplycheckpoint` flag, which sets a checkpoint at
# height 200 with known supply values.
#
# After loading the legacy cache, the node should:
# 1. Inject the checkpoint values at height 200 during LoadBlockIndexDB.
# 2. Report the correct chain supply in RPC output.
# 3. Successfully mine a new block (which requires the supply
#    consistency check to pass in ConnectBlock).
#

from test_framework.test_framework import BitcoinTestFramework
from test_framework.util import (
    NU5_BRANCH_ID,
    assert_equal,
    nuparams,
    start_nodes,
)


# Expected values at height 200 of the sprout regtest cache.
# The sprout cache has 4 x 50 ZEC = 200 ZEC shielded into Sprout.
EXPECTED_TOTAL_SUPPLY_ZAT = 214375000000
EXPECTED_TRANSPARENT_VALUE_ZAT = 194375000000
EXPECTED_SPROUT_VALUE_ZAT = 20000000000


class ChainSupplyCheckpointTest(BitcoinTestFramework):
    def __init__(self):
        super().__init__()
        self.num_nodes = 1
        self.cache_behavior = 'sprout'

    def setup_network(self, split=False):
        self.nodes = start_nodes(self.num_nodes, self.options.tmpdir, extra_args=[[
            nuparams(NU5_BRANCH_ID, 210),
            '-regtestenablezip209',
            '-regtestchainsupplycheckpoint',
        ]])

    def run_test(self):
        node = self.nodes[0]

        # The sprout cache provides 200 pre-mined blocks.
        assert_equal(node.getblockcount(), 200)

        # Verify that the checkpoint injected the chain supply values.
        block = node.getblock(node.getbestblockhash())
        chain_supply = block['chainSupply']
        assert_equal(chain_supply['chainValueZat'], EXPECTED_TOTAL_SUPPLY_ZAT)

        value_pools = {p['id']: p for p in block['valuePools']}
        assert_equal(
            value_pools['transparent']['chainValueZat'],
            EXPECTED_TRANSPARENT_VALUE_ZAT)

        # The sprout cache has 200 ZEC in the Sprout pool (4 x 50 ZEC).
        assert_equal(value_pools['sprout']['chainValueZat'], EXPECTED_SPROUT_VALUE_ZAT)
        assert_equal(value_pools['sapling']['chainValueZat'], 0)
        assert_equal(value_pools['orchard']['chainValueZat'], 0)

        # Mine a new block. This exercises ConnectBlock's supply consistency
        # check, which requires nChainTotalSupply and nChainTransparentValue
        # to be populated on the parent block.
        node.generate(1)
        assert_equal(node.getblockcount(), 201)

        # Verify that the new block's chain supply accumulated correctly.
        new_block = node.getblock(node.getbestblockhash())
        new_supply = new_block['chainSupply']
        # The supply should have increased by the block subsidy.
        assert new_supply['chainValueZat'] > EXPECTED_TOTAL_SUPPLY_ZAT


if __name__ == '__main__':
    ChainSupplyCheckpointTest().main()
