#!/usr/bin/env python3
# Copyright (c) 2026 The Zcash developers
# Distributed under the MIT software license, see the accompanying
# file COPYING or https://www.opensource.org/licenses/mit-license.php .

#
# Verify that, on regtest, loading a block index entry that lacks the chain
# supply tracking fields (`nChainTotalSupply`, `nChainTransparentValue`) and
# then connecting a new block on top of it causes the node to abort with the
# expected "Chain supply tracking fields are missing" message.
#
# (The opt-out flag `-regtestallowlegacychainsupplydata` is exercised
# implicitly by the other regtest tests that load the `sprout` cache.)
#
# The persistent `sprout` cache fixture was generated by a zcashd version
# older than `TRANSPARENT_VALUE_VERSION` (5.4.0), so its on-disk block index
# entries lack `nChainSupplyDelta` and the chain supply / transparent value
# fields cannot be reconstructed by `LoadBlockIndexDB`. Connecting a new
# block via `generate()` triggers `ConnectBlock`, which then trips the
# supply consistency check and calls `AbortNode`.
#

import os
import tempfile

from test_framework.authproxy import JSONRPCException
from test_framework.test_framework import BitcoinTestFramework
from test_framework.util import (
    NU5_BRANCH_ID,
    assert_equal,
    bitcoind_processes,
    nuparams,
    start_node,
)


ABORT_MESSAGE = "Chain supply tracking fields are missing"


class LegacyChainSupplyAbortTest(BitcoinTestFramework):
    def __init__(self):
        super().__init__()
        self.num_nodes = 1
        self.cache_behavior = 'sprout'

    def setup_network(self, split=False):
        # Note: deliberately NOT passing -regtestallowlegacychainsupplydata.
        # We enable ZIP 209 via -regtestenablezip209 because the supply
        # consistency check is gated on ZIP209Enabled().
        # Capture the node's stderr so the expected "fatal internal error"
        # message printed by AbortNode does not propagate to the test
        # framework (which would otherwise treat the test as failed).
        self.node_stderr = tempfile.SpooledTemporaryFile(max_size=2**16)
        self.nodes = [start_node(0, self.options.tmpdir, extra_args=[
            '-debug',
            nuparams(NU5_BRANCH_ID, 210),
            '-regtestenablezip209',
        ], stderr=self.node_stderr)]

    def run_test(self):
        node = self.nodes[0]

        # Sanity-check the cache.
        assert_equal(node.getblockcount(), 200)

        # Generating a new block triggers ConnectBlock, which should detect
        # the missing chain supply tracking fields and AbortNode.
        try:
            node.generate(1)
        except (JSONRPCException, ConnectionError, BrokenPipeError):
            pass  # expected: the abort tears down the RPC connection
        else:
            raise AssertionError(
                "node.generate(1) should have failed because the node was aborting"
            )

        # Wait for the node process to actually exit.
        proc = bitcoind_processes.pop(0)
        proc.wait(timeout=30)

        # Verify the abort message is in the debug log.
        debug_log = os.path.join(self.options.tmpdir, "node0", "regtest", "debug.log")
        with open(debug_log, encoding="utf8") as f:
            log = f.read()
        if ABORT_MESSAGE not in log:
            raise AssertionError(
                "expected '%s' in debug log, but it was not found" % ABORT_MESSAGE
            )

        # Prevent the test framework's cleanup from trying to RPC-stop the
        # already-dead node.
        self.nodes = []

        print("Node aborted as expected with message: %s" % ABORT_MESSAGE)


if __name__ == '__main__':
    LegacyChainSupplyAbortTest().main()
