cc_test(
    name = "wallet_tests",
    size = "small",
    srcs = ["wallet_tests.cpp"],
    deps = [
        "//src:main",
        "//src/test:test_bitcoin",
        "@boost//:foreach",
        "@boost//:test",
    ],
)
