#v5.4.2
ARG FROMBASEOS
ARG FROMBASEOS_BUILD_TAG
FROM $FROMBASEOS:$FROMBASEOS_BUILD_TAG

RUN pacman -Syyu --noconfirm \
    && pacman -Syu --noconfirm \
      base-devel \
      git \
      libunwind \
      python3 \
      python-pip \
      ncurses \
      wget

RUN sudo link /lib/libtinfo.so.6 /lib/libtinfo.so.5
