#v5.4.2
ARG FROMBASEOS
ARG FROMBASEOS_BUILD_TAG
FROM electriccoinco/zcashd-build-$FROMBASEOS-$FROMBASEOS_BUILD_TAG

COPY requirements.txt requirements.txt
RUN (mv /usr/bin/pip3 /usr/bin/pip || echo "") \
    && export PATH=$PATH:/usr/bin:/usr/local/bin/pip \
    && pip install --upgrade pip \
    && pip install -r requirements.txt

COPY ./zcash-params /home/.zcash-params
