#!/usr/bin/env python3
"""
Re-applies the MINIMAL Ironwood (NU6.3) mocks to the vendored shared Rust crates.

WHY THIS EXISTS
---------------
The shared crates (zcash_protocol, zcash_primitives, orchard, ...) are shared with
Zebra; the REAL Ironwood support in them will be implemented by others. They are NOT
the complexity this feasibility investigation measures. But the vendored copies are
regenerated by `./distclean.sh ; ./build.sh` (cargo vendor), which wipes any direct
edits. So these throwaway mocks live here as an idempotent, re-appliable script rather
than as edits to the (gitignored, regenerated) vendored tree.

Run AFTER `./build.sh` has vendored the deps, then re-run the Rust build:
    python3 ironwood-notes/crate-mocks/apply.py
    make -C src cargo-build

What it mocks (the bare minimum so zcashd's real v6/Ironwood changes can build & run):
  * zcash_protocol: a new NU6.3 NetworkUpgrade + BranchId (0x725d9e30) + LocalNetwork
    field. (Every NU6.3 tx's ZIP-244 txid/sighash is computed in this shared crate, so
    it must recognise the branch id.)
  * zcash_primitives: NU6.3 match arms + an Ironwood v6 tx header that is routed through
    the existing v5 digest machinery (the trailing Ironwood bundle bytes are ignored by
    the v5 reader). The real ZIP would commit the Ironwood bundle in the digests.

The zcashd side serializes a REAL v6 transaction and calls the digest FFI normally; the
mock lives entirely here, in the shared crates.
"""
import glob
import json
import os
import shutil
import sys

REPO = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))


CLONES = os.path.join(REPO, "ironwood-crates")


def clone_crate(name):
    """Copy a freshly-vendored crate into ironwood-crates/ if not already present.

    The clone lives OUTSIDE depends/, so it survives `./distclean.sh`. It is wired in
    via [patch.crates-io] in the root Cargo.toml (path deps are not checksum-verified)."""
    dest = os.path.join(CLONES, name)
    if os.path.isdir(dest):
        return dest
    src = None
    for v in glob.glob(os.path.join(REPO, "depends", "*", "vendored-sources")):
        cand = os.path.join(v, name)
        if os.path.isdir(cand):
            src = cand
            break
    if src is None:
        sys.exit(f"Cannot find vendored {name}; run ./build.sh first.")
    os.makedirs(CLONES, exist_ok=True)
    shutil.copytree(src, dest)
    print(f"  cloned {name} -> {os.path.relpath(dest, REPO)}")
    return dest


def patch(path, edits):
    """edits: list of (old, new). Idempotent: skip an edit whose `new` is already present."""
    with open(path) as f:
        content = f.read()
    changed = False
    for old, new in edits:
        if new in content:
            continue  # already applied
        if old not in content:
            sys.exit(f"ANCHOR NOT FOUND in {path}:\n---\n{old}\n---\n"
                     "The vendored crate version may have changed; update this script.")
        content = content.replace(old, new, 1)
        changed = True
    if changed:
        with open(path, "w") as f:
            f.write(content)
        print(f"  patched {os.path.relpath(path, REPO)}")
    else:
        print(f"  up-to-date {os.path.relpath(path, REPO)}")


def empty_checksum(crate_dir):
    p = os.path.join(crate_dir, ".cargo-checksum.json")
    if not os.path.exists(p):
        return
    d = json.load(open(p))
    if d.get("files") != {}:
        d["files"] = {}
        json.dump(d, open(p, "w"))
        print(f"  emptied checksum {os.path.relpath(p, REPO)}")


# ---------------------------------------------------------------------------
# zcash_protocol: add NU6.3 NetworkUpgrade + BranchId + LocalNetwork field.
# ---------------------------------------------------------------------------
ZP_CONSENSUS = [
    # MainNetwork::activation_height
    ("""            NetworkUpgrade::Nu6_2 => Some(BlockHeight(3_364_600)),
            #[cfg(zcash_unstable = "nu7")]
            NetworkUpgrade::Nu7 => None,""",
     """            NetworkUpgrade::Nu6_2 => Some(BlockHeight(3_364_600)),
            // NU6.3 / Ironwood (MOCK): activation height managed by zcashd C++ side.
            NetworkUpgrade::Nu6_3 => None,
            #[cfg(zcash_unstable = "nu7")]
            NetworkUpgrade::Nu7 => None,"""),
    # TestNetwork::activation_height
    ("""            NetworkUpgrade::Nu6_2 => Some(BlockHeight(4_052_000)),
            #[cfg(zcash_unstable = "nu7")]
            NetworkUpgrade::Nu7 => None,""",
     """            NetworkUpgrade::Nu6_2 => Some(BlockHeight(4_052_000)),
            // NU6.3 / Ironwood (MOCK): activation height managed by zcashd C++ side.
            NetworkUpgrade::Nu6_3 => None,
            #[cfg(zcash_unstable = "nu7")]
            NetworkUpgrade::Nu7 => None,"""),
    # NetworkUpgrade enum
    ("""    /// [Nu6.2]: https://z.cash/upgrade/nu6.2/
    Nu6_2,
    /// The [Nu7 (proposed)] network upgrade.""",
     """    /// [Nu6.2]: https://z.cash/upgrade/nu6.2/
    Nu6_2,
    /// The Nu6.3 / Ironwood network upgrade (MOCK feasibility fork).
    Nu6_3,
    /// The [Nu7 (proposed)] network upgrade."""),
    # Display
    ("""            NetworkUpgrade::Nu6_2 => write!(f, "Nu6.2"),
            #[cfg(zcash_unstable = "nu7")]
            NetworkUpgrade::Nu7 => write!(f, "Nu7"),""",
     """            NetworkUpgrade::Nu6_2 => write!(f, "Nu6.2"),
            NetworkUpgrade::Nu6_3 => write!(f, "Nu6.3"),
            #[cfg(zcash_unstable = "nu7")]
            NetworkUpgrade::Nu7 => write!(f, "Nu7"),"""),
    # branch_id()
    ("""            NetworkUpgrade::Nu6_2 => BranchId::Nu6_2,
            #[cfg(zcash_unstable = "nu7")]
            NetworkUpgrade::Nu7 => BranchId::Nu7,""",
     """            NetworkUpgrade::Nu6_2 => BranchId::Nu6_2,
            NetworkUpgrade::Nu6_3 => BranchId::Nu6_3,
            #[cfg(zcash_unstable = "nu7")]
            NetworkUpgrade::Nu7 => BranchId::Nu7,"""),
    # UPGRADES_IN_ORDER
    ("""    NetworkUpgrade::Nu6_2,
    #[cfg(zcash_unstable = "nu7")]
    NetworkUpgrade::Nu7,
];""",
     """    NetworkUpgrade::Nu6_2,
    NetworkUpgrade::Nu6_3,
    #[cfg(zcash_unstable = "nu7")]
    NetworkUpgrade::Nu7,
];"""),
    # BranchId enum
    ("""    /// The consensus rules deployed by [`NetworkUpgrade::Nu6_2`].
    Nu6_2,
    /// The consensus rules to be deployed by [`NetworkUpgrade::Nu7`].
    #[cfg(zcash_unstable = "nu7")]
    Nu7,""",
     """    /// The consensus rules deployed by [`NetworkUpgrade::Nu6_2`].
    Nu6_2,
    /// The consensus rules deployed by [`NetworkUpgrade::Nu6_3`] (Ironwood, MOCK).
    Nu6_3,
    /// The consensus rules to be deployed by [`NetworkUpgrade::Nu7`].
    #[cfg(zcash_unstable = "nu7")]
    Nu7,"""),
    # TryFrom<u32>
    ("""            0x5437_f330 => Ok(BranchId::Nu6_2),
            #[cfg(zcash_unstable = "nu7")]
            0xffff_ffff => Ok(BranchId::Nu7),""",
     """            0x5437_f330 => Ok(BranchId::Nu6_2),
            0x725d_9e30 => Ok(BranchId::Nu6_3),
            #[cfg(zcash_unstable = "nu7")]
            0xffff_ffff => Ok(BranchId::Nu7),"""),
    # From<BranchId> for u32
    ("""            BranchId::Nu6_2 => 0x5437_f330,
            #[cfg(zcash_unstable = "nu7")]
            BranchId::Nu7 => 0xffff_ffff,""",
     """            BranchId::Nu6_2 => 0x5437_f330,
            BranchId::Nu6_3 => 0x725d_9e30,
            #[cfg(zcash_unstable = "nu7")]
            BranchId::Nu7 => 0xffff_ffff,"""),
    # height_bounds
    ("""            BranchId::Nu6_2 => params
                .activation_height(NetworkUpgrade::Nu6_2)
                .map(|lower| {
                    #[cfg(zcash_unstable = "nu7")]
                    let upper = params.activation_height(NetworkUpgrade::Nu7);
                    #[cfg(zcash_unstable = "zfuture")]
                    let upper = params.activation_height(NetworkUpgrade::ZFuture);
                    #[cfg(not(any(zcash_unstable = "nu7", zcash_unstable = "zfuture")))]
                    let upper = None;
                    (lower, upper)
                }),
            #[cfg(zcash_unstable = "nu7")]
            BranchId::Nu7 => params""",
     """            BranchId::Nu6_2 => params
                .activation_height(NetworkUpgrade::Nu6_2)
                .map(|lower| (lower, params.activation_height(NetworkUpgrade::Nu6_3))),
            BranchId::Nu6_3 => params
                .activation_height(NetworkUpgrade::Nu6_3)
                .map(|lower| {
                    #[cfg(zcash_unstable = "nu7")]
                    let upper = params.activation_height(NetworkUpgrade::Nu7);
                    #[cfg(zcash_unstable = "zfuture")]
                    let upper = params.activation_height(NetworkUpgrade::ZFuture);
                    #[cfg(not(any(zcash_unstable = "nu7", zcash_unstable = "zfuture")))]
                    let upper = None;
                    (lower, upper)
                }),
            #[cfg(zcash_unstable = "nu7")]
            BranchId::Nu7 => params"""),
    # has_sprout
    ("""            Sprout | Overwinter | Sapling | Blossom | Heartwood | Canopy | Nu5 | Nu6 | Nu6_1
            | Nu6_2 => true,""",
     """            Sprout | Overwinter | Sapling | Blossom | Heartwood | Canopy | Nu5 | Nu6 | Nu6_1
            | Nu6_2 | Nu6_3 => true,"""),
    # has_sapling
    ("""            Sapling | Blossom | Heartwood | Canopy | Nu5 | Nu6 | Nu6_1 | Nu6_2 => true,
            #[cfg(zcash_unstable = "nu7")]
            BranchId::Nu7 => true,""",
     """            Sapling | Blossom | Heartwood | Canopy | Nu5 | Nu6 | Nu6_1 | Nu6_2 | Nu6_3 => true,
            #[cfg(zcash_unstable = "nu7")]
            BranchId::Nu7 => true,"""),
    # has_orchard
    ("""            Nu5 | Nu6 | Nu6_1 | Nu6_2 => true,
            #[cfg(zcash_unstable = "nu7")]
            BranchId::Nu7 => true,""",
     """            Nu5 | Nu6 | Nu6_1 | Nu6_2 | Nu6_3 => true,
            #[cfg(zcash_unstable = "nu7")]
            BranchId::Nu7 => true,"""),
    # arb_branch_id (test-dependencies; harmless to patch)
    ("""            BranchId::Nu6_2,
            #[cfg(zcash_unstable = "nu7")]
            BranchId::Nu7,
            #[cfg(zcash_unstable = "zfuture")]
            BranchId::ZFuture,
        ])""",
     """            BranchId::Nu6_2,
            BranchId::Nu6_3,
            #[cfg(zcash_unstable = "nu7")]
            BranchId::Nu7,
            #[cfg(zcash_unstable = "zfuture")]
            BranchId::ZFuture,
        ])"""),
]

ZP_LOCAL = [
    # LocalNetwork struct field
    ("""    pub nu6_2: Option<BlockHeight>,
    #[cfg(zcash_unstable = "nu7")]
    pub nu7: Option<BlockHeight>,""",
     """    pub nu6_2: Option<BlockHeight>,
    pub nu6_3: Option<BlockHeight>,
    #[cfg(zcash_unstable = "nu7")]
    pub nu7: Option<BlockHeight>,"""),
    # LocalNetwork::activation_height
    ("""            NetworkUpgrade::Nu6_2 => self.nu6_2,
            #[cfg(zcash_unstable = "nu7")]
            NetworkUpgrade::Nu7 => self.nu7,""",
     """            NetworkUpgrade::Nu6_2 => self.nu6_2,
            NetworkUpgrade::Nu6_3 => self.nu6_3,
            #[cfg(zcash_unstable = "nu7")]
            NetworkUpgrade::Nu7 => self.nu7,"""),
]

# ---------------------------------------------------------------------------
# zcash_primitives: NU6.3 match arms + Ironwood v6 header -> v5 digest machinery.
# ---------------------------------------------------------------------------
ZPRIM_TX = [
    # Ironwood constants after the V5 constants import.
    ("""use zcash_protocol::constants::{
    V3_TX_VERSION, V3_VERSION_GROUP_ID, V4_TX_VERSION, V4_VERSION_GROUP_ID, V5_TX_VERSION,
    V5_VERSION_GROUP_ID,
};""",
     """use zcash_protocol::constants::{
    V3_TX_VERSION, V3_VERSION_GROUP_ID, V4_TX_VERSION, V4_VERSION_GROUP_ID, V5_TX_VERSION,
    V5_VERSION_GROUP_ID,
};

// NU6.3 / Ironwood (MOCK): a feasibility transaction version whose body mirrors the
// v5 layout with a trailing Ironwood Orchard bundle. The real ZIP would commit the
// Ironwood bundle in the ZIP-244 digests; this mock routes v6 Ironwood transactions
// through the existing v5 digest/sighash machinery (the v5 reader ignores the trailing
// Ironwood bytes). These MUST match zcashd's IRONWOOD_VERSION_GROUP_ID /
// IRONWOOD_TX_VERSION in src/primitives/transaction.h.
const IRONWOOD_TX_VERSION: u32 = 6;
const IRONWOOD_VERSION_GROUP_ID: u32 = 0x7777_7777;"""),
    # TxVersion::read
    ("""                (V5_TX_VERSION, V5_VERSION_GROUP_ID) => Ok(TxVersion::V5),
                #[cfg(zcash_unstable = "nu7")]
                (V6_TX_VERSION, V6_VERSION_GROUP_ID) => Ok(TxVersion::V6),""",
     """                (V5_TX_VERSION, V5_VERSION_GROUP_ID) => Ok(TxVersion::V5),
                // NU6.3 / Ironwood (MOCK): treat the v6 Ironwood header as v5 for digest
                // purposes; the trailing Ironwood bundle is ignored by the v5 reader.
                (IRONWOOD_TX_VERSION, IRONWOOD_VERSION_GROUP_ID) => Ok(TxVersion::V5),
                #[cfg(zcash_unstable = "nu7")]
                (V6_TX_VERSION, V6_VERSION_GROUP_ID) => Ok(TxVersion::V6),"""),
    # suggested_for_branch
    ("""            BranchId::Nu6_2 => TxVersion::V5,
            #[cfg(zcash_unstable = "nu7")]
            BranchId::Nu7 => TxVersion::V6,""",
     """            BranchId::Nu6_2 => TxVersion::V5,
            BranchId::Nu6_3 => TxVersion::V5,
            #[cfg(zcash_unstable = "nu7")]
            BranchId::Nu7 => TxVersion::V6,"""),
    # valid_in_branch V4
    ("""                Sapling | Blossom | Heartwood | Canopy | Nu5 | Nu6 | Nu6_1 | Nu6_2 => true,
                #[cfg(zcash_unstable = "nu7")]
                Nu7 => false, // ZIP 2003""",
     """                Sapling | Blossom | Heartwood | Canopy | Nu5 | Nu6 | Nu6_1 | Nu6_2 | Nu6_3 => true,
                #[cfg(zcash_unstable = "nu7")]
                Nu7 => false, // ZIP 2003"""),
    # valid_in_branch V5
    ("""                Sprout | Overwinter | Sapling | Blossom | Heartwood | Canopy => false,
                Nu5 | Nu6 | Nu6_1 | Nu6_2 => true,
                #[cfg(zcash_unstable = "nu7")]
                Nu7 => true,""",
     """                Sprout | Overwinter | Sapling | Blossom | Heartwood | Canopy => false,
                Nu5 | Nu6 | Nu6_1 | Nu6_2 | Nu6_3 => true,
                #[cfg(zcash_unstable = "nu7")]
                Nu7 => true,"""),
    # read_v5 proof enforcement
    ("""                | BranchId::Nu6_1 => ProofSizeEnforcement::Unenforced,
                BranchId::Nu6_2 => ProofSizeEnforcement::Strict,
                #[cfg(zcash_unstable = "nu7")]
                BranchId::Nu7 => ProofSizeEnforcement::Strict,""",
     """                | BranchId::Nu6_1 => ProofSizeEnforcement::Unenforced,
                BranchId::Nu6_2 => ProofSizeEnforcement::Strict,
                BranchId::Nu6_3 => ProofSizeEnforcement::Strict,
                #[cfg(zcash_unstable = "nu7")]
                BranchId::Nu7 => ProofSizeEnforcement::Strict,"""),
    # arb_tx_version
    ("""            BranchId::Nu6_2 => Just(TxVersion::V5).boxed(),
            #[cfg(zcash_unstable = "nu7")]
            BranchId::Nu7 => Just(TxVersion::V6).boxed(),""",
     """            BranchId::Nu6_2 => Just(TxVersion::V5).boxed(),
            BranchId::Nu6_3 => Just(TxVersion::V5).boxed(),
            #[cfg(zcash_unstable = "nu7")]
            BranchId::Nu7 => Just(TxVersion::V6).boxed(),"""),
]


def main():
    zp = clone_crate("zcash_protocol")
    patch(os.path.join(zp, "src", "consensus.rs"), ZP_CONSENSUS)
    patch(os.path.join(zp, "src", "local_consensus.rs"), ZP_LOCAL)
    zprim = clone_crate("zcash_primitives")
    patch(os.path.join(zprim, "src", "transaction", "mod.rs"), ZPRIM_TX)
    print()
    print("Clones patched. Root Cargo.toml must contain:")
    print("  [patch.crates-io]")
    print('  zcash_protocol = { path = "ironwood-crates/zcash_protocol" }')
    print('  zcash_primitives = { path = "ironwood-crates/zcash_primitives" }')
    print("Then: cargo generate-lockfile --offline && make -C src cargo-build")


if __name__ == "__main__":
    main()
