/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "Crypto-Conditions"
 * 	found in "CryptoConditions.asn"
 */

#ifndef	_AuxSha512Fulfillment_H_
#define	_AuxSha512Fulfillment_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* AuxSha512Fulfillment */
typedef struct AuxSha512Fulfillment {
	OCTET_STRING_t	 method;
	OCTET_STRING_t	 conditionAux;
	OCTET_STRING_t	 fulfillmentAux;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} AuxSha512Fulfillment_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AuxSha512Fulfillment;

#ifdef __cplusplus
}
#endif

#endif	/* _AuxSha512Fulfillment_H_ */
#include <asn_internal.h>
