/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "Crypto-Conditions"
 * 	found in "CryptoConditions.asn"
 */

#ifndef	_ConditionTypes_H_
#define	_ConditionTypes_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BIT_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ConditionTypes {
	ConditionTypes_preImageSha256	= 0,
	ConditionTypes_prefixSha256	= 1,
	ConditionTypes_thresholdSha256	= 2,
	ConditionTypes_rsaSha256	= 3,
	ConditionTypes_ed25519Sha256	= 4,
	ConditionTypes_secp256k1Sha256	= 5,
	ConditionTypes_evalSha256	= 15
} e_ConditionTypes;

/* ConditionTypes */
typedef BIT_STRING_t	 ConditionTypes_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ConditionTypes;
asn_struct_free_f ConditionTypes_free;
asn_struct_print_f ConditionTypes_print;
asn_constr_check_f ConditionTypes_constraint;
ber_type_decoder_f ConditionTypes_decode_ber;
der_type_encoder_f ConditionTypes_encode_der;
xer_type_decoder_f ConditionTypes_decode_xer;
xer_type_encoder_f ConditionTypes_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _ConditionTypes_H_ */
#include <asn_internal.h>
