/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "Crypto-Conditions"
 * 	found in "CryptoConditions.asn"
 */

#ifndef	_PrefixFulfillment_H_
#define	_PrefixFulfillment_H_


#include "asn_application.h"

/* Including external dependencies */
#include <OCTET_STRING.h>
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct Fulfillment;

/* PrefixFulfillment */
typedef struct PrefixFulfillment {
	OCTET_STRING_t	 prefix;
	unsigned long	 maxMessageLength;
	struct Fulfillment	*subfulfillment;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PrefixFulfillment_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_maxMessageLength_3;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_PrefixFulfillment;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "Fulfillment.h"

#endif	/* _PrefixFulfillment_H_ */
#include <asn_internal.h>
