#!/bin/bash
source pubkey.txt
args=("$@")
seed_ip='78.47.196.146'
komodo_binary='./komodod'
delay=20

function komodo_asset ()
{
    if [ $[RANDOM % 10] == 1 ]
    then
        gen=" -gen"
    else
        gen=""
    fi

    if [ -n "$2" ]
    then
        supply=" -ac_supply=$2"
    else
        supply=" "
    fi

    $komodo_binary -pubkey=$pubkey -ac_name=$1 $supply -addnode=$seed_ip $gen $args &
    sleep $delay
}

#set -x

komodo_asset REVS 1300000
komodo_asset SUPERNET 816061
komodo_asset DEX 999999
komodo_asset PANGEA 999999
komodo_asset JUMBLR 999999
komodo_asset BET 999999
komodo_asset CRYPTO 999999
komodo_asset HODL 9999999
komodo_asset SHARK 1401
komodo_asset BOTS 999999
komodo_asset MGW 999999
#komodo_asset MVP 1000000
komodo_asset COQUI 72000000
komodo_asset WLC 210000000
komodo_asset KV 1000000
komodo_asset CEAL 366666666
komodo_asset MESH 1000007

komodo_asset USD
komodo_asset EUR
komodo_asset JPY
komodo_asset GBP
komodo_asset AUD
komodo_asset CAD
komodo_asset CHF
komodo_asset NZD
komodo_asset CNY
komodo_asset RUB
komodo_asset MXN
komodo_asset BRL
komodo_asset INR
komodo_asset HKD
komodo_asset TRY
komodo_asset ZAR
komodo_asset PLN
komodo_asset NOK
komodo_asset SEK
komodo_asset DKK
komodo_asset CZK
komodo_asset HUF
komodo_asset ILS
komodo_asset KRW
komodo_asset MYR
komodo_asset PHP
komodo_asset RON
komodo_asset SGD
komodo_asset THB
komodo_asset BGN
komodo_asset IDR
komodo_asset HRK
