#!/bin/bash
set -euo pipefail

source pubkey.txt
assetchain_args=`jq -r '.[].params' assetchains.json`
overide_args=("$@")
seed_ip=`getent hosts zero.kolo.supernet.org | awk '{ print $1 }'`
komodo_binary='./komodod'
delay=20

while read args; do
  gen=""
  if [ $[RANDOM % 10] == 1 ]; then
      gen=" -gen"
  fi

  $komodo_binary $gen $args $overide_args -pubkey=$pubkey -addnode=$seed_ip &
  sleep $delay
done <<< "$assetchain_args"
