#!/bin/bash
# Copyright (c) 2019 Hush developers

# set working directory to the location of this script
DIR="$( cd "$( dirname "$( readlink -f "${BASH_SOURCE[0]}" )" )" && pwd )"
cd $DIR

NAME=HUSH3
# this corresponds to FR address RHushEyeDm7XwtaTWtyCbjGQumYyV8vMjn
SCRIPT=76a9145eb10cf64f2bab1b457f1f25e658526155928fac88ac

# Chain parameters
ERAS=3
BLOCKTIME=150
# 6250000 - (sprout pool at block 500,000)
SUPPLY=6178674
FOUNDERS=1
REWARD=0,1125000000,562500000
PERC=11111111
HALVING=129,340000,840000
# NOTE: keep in sync with komodo_bitcoind.h
END=128,340000,5422111
CLIENTNAME=GoldenSandtrout
SEEDNODE1=188.165.212.101
SEEDNODE2=136.243.227.142
SEEDNODE3=5.9.224.250
CCLIB=hush3

# CryptoConditions/Custom Consensus params
FAUCET=228
HEIR=234
CHANNEL=235
ORACLE=236
GATEWAY=241
CCENABLE=$FAUCET,$HEIR,$CHANNEL,$ORACLE,$GATEWAY

KMD=${KOMODOD:-./komodod}
$KMD -ac_name=$NAME -ac_sapling=1                \
     -ac_reward=$REWARD                          \
     -ac_halving=$HALVING                        \
     -ac_end=$END                                \
     -ac_eras=$ERAS                              \
     -ac_blocktime=$BLOCKTIME                    \
     -ac_cc=2 -ac_ccenable=$CCENABLE             \
     -ac_founders=$FOUNDERS -ac_supply=$SUPPLY   \
     -ac_perc=$PERC                              \
     -clientname=$CLIENTNAME                     \
     -addnode=$SEEDNODE1                         \
     -addnode=$SEEDNODE2                         \
     -addnode=$SEEDNODE3                         \
     -ac_cclib=$CCLIB                            \
     -ac_script=$SCRIPT  "$@"
